language: java
script:
  - git clone https://github.com/csie-asia-Java-Programming-1/TestingData.git
  - cp -r TestingData/week06-20161031/ week06-20161031/bot/
  - cd week06-20161031/
  - chmod +x bot/TA.sh
  - ./bot/TA.sh